Возьмите датасет про пингвинов

In [4]:
import seaborn as sns
df = sns.load_dataset('penguins')
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

# Задание

1. Возьмите датасет пингвино. Уменьшите размерность от 4 до 2 признаков при помощи PCA.
    - Укажите процент объяснённой дисперсии 1 и 2 компонентами.
    - Выведите матрицу коэффициентов преобразования.
    - Постройте двумерный график наблюдений. 
    - Постройте двумерный график коэффициентов.
2. Возьмите датасет лиц: from sklearn.datasets import fetch_olivetti_faces
    - Уменьшите размерность до двух при помощи PCA
    - Уменьшите размерность до двух при помощи TSNE
    - Уменьшите размерность до двух при помощи UMAP
    Сравните результаты. Сколько главных компоеннт нужно оставить в PCA и UMAP, чтобы
    сохранить 99: дисперсии?